== Summary
This discussion paper presents an approach to harmonize GeoPackage and OWS Context. GeoPackage is an open, standards-based, platform-independent, portable, self-describing, compact format for storing and transferring geospatial data and information. 
OWS Context is an open format linking geospatial web services and information.
Through extensions, these two formats can work together.
A draft standard has been produced (see <<GPKG-OWC-draft>>).
This document is designed to be a companion to that draft standard to assist in discussion. 

This document is the work of collaboration between the GeoPackage and OWS Context Standards Working Groups (SWGs).

=== Requirements & Research Motivation
GeoPackage and OWS Context are two OGC encoding standards that have potentially complementary and overlapping uses. There are two use cases that the submitters of this discussion paper would like to see supported in a standards-based way:

1. Encoding of OWS Context content within a GeoPackage, so that a GeoPackage can load a list of OWS Contexts, present them to the user, and allow the user to select the one which most closely matches their desired activity. This would allow the OWS Context to act as a standards-based project file for GeoPackage.
2. Encoding of GeoPackage content within an OWS Context file, so that an OWS Context can refer to GeoPackage content in the same way it can refer to services, files (e.g., GML), and inline content. This would increase the utility of OWS Context because GeoPackage is becoming an increasingly common container for geospatial data and information.

In addition, the intent of the OWS Context extensions is to design them in such a way that they will work with generic relational databases, not just SQL-based GeoPackage. 

=== Prior-After Comparison
Before this work, these two standards were completely independent of each other. There was neither a standard way to encode an OWS Context in a GeoPackage nor a standard way to reference GeoPackage content in an OWS Context. 

In 2014 there was an attempt at a joint OWS Context / GeoPackage SWG, but this effort did not lead to any concrete work products.

There is a community extension (<<GPKG-OWC-community>>) that allows for OWS Context files to be stored within a GeoPackage. However, this community extension encodes OWS Context content as either a JSON or Atom document and GeoPackage developers have stated that they prefer to work entirely in the SQL domain as much as possible. 

=== Recommendations for Future Work
If the approach described by this document is embraced by the relevant SWGs, the effort should culminate in a new OGC standard. This standard would be an extension to both the GeoPackage encoding standard and the OWS Context encoding standard. (Note that as far as the submitters are aware, this is the first time OGC has attempted to produce a standard that is an extension to two different standards.)

The encoding of style information as part of this extension remains undefined. This is dependent on ongoing efforts by the Styled Layer Descriptor (SLD) SWG and other activities as described by the Portrayal Concept Development Study <<PCDS>>.

===	Document contributor contact points

All questions regarding this document should be directed to the editor or the contributors:

*Contacts*
[width="80%",options="header",caption=""]
|====================
|Name |Organization
|Jeff Yutzler (editor) | Image Matters LLC
|((contributor)) | ((from org))
|====================


// *****************************************************************************
// Editors please do not change the Foreword.
// *****************************************************************************
=== Foreword

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
